[package]
name = "qtlib"
version = "0.1.0"
authors = ["mrlynch"]
edition = "2018"

[lib]
name = "arrowpaperrust"
crate-type = ["staticlib"]

[dependencies]
libc = "0.2.58"
arrowpaperlib = { path = "../lib" }